
module.exports = [
    {
      date: "April 1",
      name: "Income",
      amount: 1000,
      from: "Employer",
      category: "Savings",
      description: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      date: "April 1",
      name: "MetroCard",
      amount: -120,
      from: "MTA",
      category: "Transportation",
      description: "",
    },
    {
      date: "April 1",
      name: "Retirement",
      amount: -200,
      from: "Employer",
      category: "Savings",
      description: "",
    },
    {
      date: "April 1",
      name: "Withdrawal",
      amount: -100,
      from: "Your Name",
      category: "Savings",
      description: "",
    },
    {
      date: "April 1",
      name: "Credit Card Payment",
      amount: -100,
      from: "Bank",
      category: "Debt",
      description: "",
    },
    {
      date: "April 5",
      name: "Birthday Money",
      amount: 20,
      from: "Bank",
      category: "Savings",
      description: "",
    },
    {
      date: "April 5",
      name: "Coffee",
      amount: -4,
      from: "Grocery-Store",
      category: "Food",
      description: "",
    },
    {
      date: "April 5",
      name: "Internet",
      amount: -100,
      from: "Internet Service Provider",
      category: "Utilities",
      description: "",
    },
    {
      date: "April 3",
      name: "Groceries",
      amount: -76,
      from: "Trader Joe's",
      category: "Food",
      description: "",
    },
    {
      date: "April 3",
      name: "Rubber Ducky Food",
      amount: -7,
      from: "Pet-Store",
      category: "Pet Care",
      description: "",
    },
  ];