
module.exports = [
    {
      date: "April 1",
      source: "Income",
      amount: 1000,
      from: "Employer",
      category: "Income",
    },
    {
      date: "April 1",
      source: "Taxes",
      amount: -300,
      from: "Uncle-Sam",
      category: "Taxes",
    },
    {
      date: "April 1",
      source: "Retirement",
      amount: -200,
      from: "Employer",
      category: "Savings",
    },
    {
      date: "April 1",
      source: "Savings",
      amount: -100,
      from: "Bank",
      category: "Savings",
    },
    {
      date: "April 1",
      source: "Credit Card Payment",
      amount: -100,
      from: "Bank",
      category: "Bills",
    },
    {
      date: "April 5",
      source: "Monthly Birthday Money from Aunt Tilda",
      amount: 20,
      from: "Bank",
      category: "Savings",
    },
    {
      date: "April 5",
      source: "Coffee",
      amount: -4,
      from: "Grocery-Store",
      category: "Food",
    },
    {
      date: "April 5",
      source: "Internet",
      amount: -100,
      from: "Internet Service Provider",
      category: "Bills",
    },
    {
      date: "April 3",
      source: "Groceries",
      amount: -76,
      from: "Grocery-Store",
      category: "Food",
    },
    {
      date: "April 3",
      source: "Pet Food",
      amount: -7,
      from: "Pet-Store",
      category: "Pet",
    },
  ];